// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB5f36epDU0OaZoOLps30NnIM4n0oWHXw',
    appId: '1:658333224351:web:c159b4101c84218bccc1aa',
    messagingSenderId: '658333224351',
    projectId: 'smarthealth-e25a7',
    authDomain: 'smarthealth-e25a7.firebaseapp.com',
    storageBucket: 'smarthealth-e25a7.firebasestorage.app',
    measurementId: 'G-87WY0J6F7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDGWFBDlReMSWOAkUI0iegUVamG2i2A_g',
    appId: '1:658333224351:android:99c37fcd47c2cc57ccc1aa',
    messagingSenderId: '658333224351',
    projectId: 'smarthealth-e25a7',
    storageBucket: 'smarthealth-e25a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8SWiZmNF5s1zToE0kgb5AAVTLzFZoQNE',
    appId: '1:658333224351:ios:423321431fa43984ccc1aa',
    messagingSenderId: '658333224351',
    projectId: 'smarthealth-e25a7',
    storageBucket: 'smarthealth-e25a7.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8SWiZmNF5s1zToE0kgb5AAVTLzFZoQNE',
    appId: '1:658333224351:ios:423321431fa43984ccc1aa',
    messagingSenderId: '658333224351',
    projectId: 'smarthealth-e25a7',
    storageBucket: 'smarthealth-e25a7.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB5f36epDU0OaZoOLps30NnIM4n0oWHXw',
    appId: '1:658333224351:web:5bceea560d875eb2ccc1aa',
    messagingSenderId: '658333224351',
    projectId: 'smarthealth-e25a7',
    authDomain: 'smarthealth-e25a7.firebaseapp.com',
    storageBucket: 'smarthealth-e25a7.firebasestorage.app',
    measurementId: 'G-T8NYM108VW',
  );

}